.TH ACQ 6 "August 2016" "Manual page for acq"
.SH NAME
.B acq
\- interrogate AC, the interplanetary computer
.SH USAGE
$
.B acq
.br
How may the stars be prevented from going out?
.SH DESCRIPTION
.B acq
allows you to pose questions to AC, the interplanetary computer. Suggested
topics include the inevitable fate of the universe and whether its ultimate
destruction through entropy is truly inevitable.
.SH SEE ALSO
<http://multivax.com/last_question.html>
.SH AUTHOR
Tom Ryder <tom@sanctum.geek.nz>
