.TH DR 6 "August 2016" "Manual page for dr"
.SH NAME
.B dr
\- roll D&D dice
.SH USAGE
.B dr
d6
.br
.B dr
2d12
.br
.B dr
3d4+10
.SH DESCRIPTION
.B dr
rolls dice according to the formulas used in D&D and other tabletop roleplaying
games. It only allows d4, d6, d8, d10, d12, and d20 dice.
.SH SEE ALSO
rndi(1)
.SH AUTHOR
Tom Ryder <tom@sanctum.geek.nz>
