.TH KVLT 6 "June 2016" "Manual page for kvlt"
.SH NAME
.B kvlt
\- sound like a 14-year-old who just listened to "A Blaze in the Northern Sky"
for the first time
.SH USAGE
.B kvlt
/usr/share/dict/words
.br
lynx -dump https://sanctum.geek.nz/ |
.B kvlt
.SH DESCRIPTION
.B kvlt
emulates a style of typing that seems to be unique to black metal communities
on the internet, chiefly (as I remember it) +BlackMetal+ on Soulseek.
.SH AUTHOR
Tom Ryder <tom@sanctum.geek.nz>
