.TH RNDN 6 "June 2016" "Manual page for rndn"
.SH NAME
.B rndn
\- esoteric random number generator
.SH USAGE
.B rndn
.br
.B rndn -s 381290
.br
business-critical-process -t "$(\fBrndn\fR)"
.SH DESCRIPTION
.B rndn
uses an advanced but somewhat esoteric algorithm derived by Adams (2001) to
return a random number. The seed can be derived internally or specified with
the -s option.
.P
While rndn(6) has proven robust in the author's production usage, its algorithm
has not been formally verified.
.SH SEE ALSO
<http://dilbert.com/strip/2001-10-25>
.br
rndi(1), rnda(1), rndf(1)
.SH AUTHORS
Tom Ryder <tom@sanctum.geek.nz>
.br
Inspired by discussions with Wade Brown
