.TH SYL 6 "June 2016" "Manual page for syl"
.SH NAME
.B syl
\- make a crude guess as to the number of syllables of a word
.SH USAGE
.B syl
syllable
.br
.B syl
canapé
.SH DESCRIPTION
.B syl
applies some very crude heuristics to guess at the number of syllables that
would be used if the Latin-alphabet word on the command line were spoken out
loud. It is far too inaccurate for any serious use, particularly for languages
other than English; the author uses it for poetry generation.
.SH AUTHOR
Tom Ryder <tom@sanctum.geek.nz>
