.TH XYZZY 6 "August 2016" "Manual page for xyzzy"
.SH NAME
.B xyzzy
\- teleport between directories
.SH USAGE
.B xyzzy
.SH DESCRIPTION
Invoking
.B xyzzy
in a directory will tag that directory as a target for teleportation, writing
its name to the file ~/.xyzzy. Typing it again at any given point will then
change into that marked directory.
.SH AUTHOR
Tom Ryder <tom@sanctum.geek.nz>
