#!/bin/sh
for bin in bin/* ; do
    hb=$(sed 1q "$bin") || exit
    case $hb in
        *bash)
            bash -n "$bin" || exit 1
            ;;
        *sh)
            sh -n "$bin" || exit 1
            ;;
        *'sed -f')
            sed -f "$bin" /dev/null >/dev/null || exit 1
            ;;
        *'awk -f')
            # Not sure how to test these yet
            ;;
        *)
            printf 2>&1 'Unknown hashbang for %s\n' "$bin"
            exit 1
            ;;
    esac
done
printf 'All shell scripts in bin parsed successfully.\n'
