#!/bin/sh
for game in games/* ; do
    [ -f "$game" ] || continue
    hb=$(sed 1q "$game") || exit
    case $hb in
        *bash)
            bash -n "$game" || exit
            ;;
        *sh)
            sh -n "$game" || exit
            ;;
        *'sed -f')
            sed -f "$game" /dev/null >/dev/null || exit
            ;;
        *'awk -f')
            # Not sure how to test these yet
            ;;
        *)
            printf 2>&1 'Unknown hashbang for %s\n' "$game"
            exit 1
            ;;
    esac
done
printf 'All shell scripts in games parsed successfully.\n'
