#!/bin/sh
for bin in bin/* ; do
    [ -x "$bin" ] || continue
    hb=$(sed 1q "$bin") || exit
    case $hb in
        *bash)
            bash -n "$bin" || exit
            ;;
        *sh)
            sh -n "$bin" || exit
            ;;
    esac
done
printf 'All shell scripts in bin parsed successfully.\n'
