#!/bin/sh
for game in games/* ; do
    [ -x "$game" ] || continue
    hb=$(sed 1q "$game") || exit
    case $hb in
        *bash)
            bash -n "$game" || exit
            ;;
        *sh)
            sh -n "$game" || exit
            ;;
    esac
done
printf 'All shell scripts in games parsed successfully.\n'
