#!/bin/sh
for perl in urxvt/ext/* ; do
    [ -f "$perl" ] || continue
    case $perl in
        *.pl) ;;
        *) perl -c "$perl" >/dev/null || exit ;;
    esac
done
printf 'All Perl scripts in urxvt/ext parsed successfully.\n'
