#!/usr/bin/env bash
hash syl || exit
declare -a lsts ws
lsts=(5 7 5)
for ((lc=0;lc<${#lsts[@]};lc++)) ; do
    ws=()
    for ((sc=0;sc<lsts[lc];)) ; do
        read -r wr
        sy=$(syl "$wr")
        ((sy<=lsts[lc]-sc)) || continue
        ws[${#ws[@]}]=$wr
        ((sc+=sy))
    done
    printf '%s\n' "${ws[*]}"
done < <(shuf "${@:-/usr/share/dict/words}" |
    grep -v \'s\$) |
    tr '[:upper:]' '[:lower:]'
