#!/usr/bin/env bash
cat -- "${@:-/dev/stdin}" |
while read -r -a ws ; do
    for w in "${ws[@]}" ; do
        w=${w%%[^a-zA-Z]*}
        w=${w##*[^a-zA-Z]}
        [[ $w ]] || continue
        printf '%s\n' "$w"
    done
done | tr '[:upper:]' '[:lower:]'
