#!/bin/sh
for bin in bin/* ; do
    [ -f "$bin" ] || continue
    hb=$(sed 1q "$bin") || exit
    case $hb in
        *sh)
            printf '%s\n' "$bin"
            shellcheck -- "$bin"
            ;;
    esac
done
