#!/bin/sh
for game in games/* ; do
    [ -e "$game" ] || continue
    hb=$(sed 1q "$game") || exit
    case $hb in
        *sh)
            printf '%s\n' "$game"
            shellcheck -- "$game"
            ;;
    esac
done
