" My choice of font changes depending on which operating system I'm using;
" these are both workable monospace fonts, but Ubuntu Mono doesn't render very
" nicely on Windows a lot of the time
if has('unix')
  silent! let &guifont = 'Ubuntu Mono 12'
else
  silent! let &guifont = 'Consolas:h11'
endif

" Reset guioptions
set guioptions=
" Use the system GUI clipboard
set guioptions+=a
" Use console dialogs instead of popup windows
set guioptions+=c
" Use the gVim icon
set guioptions+=i

" When the GUI starts, t_vb is reset to its default value, so it's necessary
" to repeat this line from my .vimrc file that turns off visual bells
set visualbell t_vb=
