" Ubuntu Mono on Unix, Consolas on Windows
if has('unix')
  set guifont=Ubuntu\ Mono\ 12
elseif has('win32') || has('win64')
  set guifont=Consolas:h11,Courier\ New:h11
endif

" Reset GUI options
set guioptions=
set guioptions+=a  " Use the system GUI clipboard
set guioptions+=c  " Use console dialogs, not popup windows
set guioptions+=M  " Don't load menu.vim (also set in .vimrc)

" Don't use the mouse
set mouse=

" Stamp 'visualbell' back down again, if 'belloff' not available
if !exists('+belloff')
  set visualbell t_vb=
endif
