.TH SUE 8 "September 2015" "Manual page for sue"
.SH NAME
.B sue
\- run sudoedit(8) as the arguments' owner
.SH SYNOPSIS
.B sue
FILE1 [FILE2...]
.SH DESCRIPTION
Run sudoedit(8) over the arguments given as the user that owns them all; exit
with an error if they're not owned by a common user. This could be useful in
situations where you don't have full root access via sudo(8), or simply want
to be strict about working with least privilege.
.SH AUTHOR
Tom Ryder <tom@sanctum.geek.nz>

