# Emacs-style key bindings
set -o braceexpand
set -o emacs

# Save history
HISTFILE=$HOME/.ksh_history
HISTSIZE=$((1 << 10))

# If HOST and HOSTNAME aren't set by this version of ksh, set them
HOSTNAME=$(uname -n)
HOST=${HOSTNAME%%.*}

# Load any supplementary scripts
for kshrc in "$HOME"/.kshrc.d/*.ksh ; do
    [[ -e $kshrc ]] && . "$kshrc"
done
unset -v kshrc
