# Emacs-style key bindings
set -o braceexpand
set -o emacs

# Save history
HISTFILE=$HOME/.ksh_history
HISTSIZE=$((1 << 10))

# Load any supplementary scripts
for kshrc in "$HOME"/.kshrc.d/*.ksh ; do
    [[ -e $kshrc ]] && . "$kshrc"
done
unset -v kshrc
