# Read X resources
xrdb "$HOME"/.Xresources

# Map Caps Lock as a Ctrl key, use right alt as Compose, kill X server with
# Ctrl+Alt+Backspace
# <https://en.wikipedia.org/wiki/Compose_key#Common_compose_combinations>
setxkbmap -option compose:ralt,ctrl:nocaps,terminate:ctrl_alt_bksp

# Apply background image
# Edited cover of Darkthrone's 1994 album "Transilvanian Hunger"
feh --bg-scale --no-fehbg -- "$HOME"/.xbackgrounds/hunger.jpg

# Start dunst(1) to display libnotify messages
dunst &

# Start mpdlrc-notify-send <https://github.com/tejr/mpdlrc/>
mpdlrc-notify-send &

# Start redshift(1)
redshift &

# Start urxvtd(1)
urxvtd -o -q &

# Start xbindkeys(1)
xbindkeys -n &

# Start window manager
exec i3

