# Read X resources
xrdb "$HOME"/.Xresources

# Map Caps Lock as a Ctrl key, use right alt as Compose
# <https://en.wikipedia.org/wiki/Compose_key#Common_compose_combinations>
setxkbmap -option ctrl:nocaps -option compose:ralt

# Apply background image
feh --bg-scale --no-fehbg -- "$HOME"/.xbackgrounds/castle.jpg

# Start redshift(1)
redshift &

# Start urxvtd(1)
urxvtd -o -q &

# Start xbindkeys(1)
xbindkeys -n &

# Start window manager
exec i3

