# Emacs keybindings even if EDITOR is vi(1)
bindkey -e

# Clear away all aliases; we do this here rather than in $ENV because the ksh
# family of shells relies on aliases to implement certain POSIX utilities like
# fc(1) and type(1)
unalias -a

# If ENV is set, source it to get all the POSIX-compatible interactive stuff
[[ -n $ENV ]] && source "$ENV"

# History settings
setopt histignorealldups sharehistory
HISTFILE=$HOME/.zsh_history
SAVEHIST=$((1 << 12))

# Load Zsh-specific startup files
for sh in "$HOME"/.zshrc.d/*.zsh ; do
    [[ -e $sh ]] && source "$sh"
done
unset -v sh
