# Emacs keybindings even if EDITOR is vi(1)
bindkey -e

# History settings
setopt histignorealldups sharehistory
HISTFILE=$HOME/.zsh_history
SAVEHIST=$((1 << 12))
HISTSIZE=$((1 << 10))

# Load POSIX shell startup files and then Bash-specific ones
for sh in "$ENV" "$HOME"/.zshrc.d/*.zsh ; do
    [[ -e $sh ]] && source "$sh"
done
unset -v sh
