.TH BR 1 "August 2016" "Manual page for br"
.SH NAME
.B br
\- launch "$BROWSER"
.SH SYNOPSIS
.B br
.br
BROWSER=firefox
.B br
.SH DESCRIPTION
.B br
execs the program in the $BROWSER environment variable. That's it. It was
written so the browser could safely be launched from xbindkeys(1) and similar
programs.
.SH AUTHOR
Tom Ryder <tom@sanctum.geek.nz>
