.TH D2U 1 "August 2016" "Manual page for d2u"
.SH NAME
.B d2u
\- change text files from DOS to UNIX format
.SH USAGE
.B d2u FILE1 [FILE2 ...]
.SH DESCRIPTION
Applies ed(1) to change DOS \\r\\n (CRLF) line endings to UNIX \\n line
endings. Files already in UNIX format should be unchanged.
.SH SEE ALSO
ed(1), u2d(1)
.SH AUTHOR
Tom Ryder <tom@sanctum.geek.nz>
