.TH DMP 1 "May 2014" "Manual page for dmp"
.SH NAME
.B dmp
\- pick a pass(1) password with dmenu(1)
.SH SYNOPSIS
.B dmp
.SH DESCRIPTION
.B dmp
applies dmenu(1) to pick a password entry
from a pass(1) store and put it into the X
CLIPBOARD for up to 10 seconds.
.SH SEE ALSO
dmenu(1), pass(1)
.SH AUTHOR
Tom Ryder <tom@sanctum.geek.nz>
