.TH VIS 1 "November 2015" "Manual page for eds"
.SH NAME
.B eds
\- create and edit personal scripts
.SH SYNOPSIS
.B eds [EDITOR_OPTS] [--] FILE1 [FILE2...]
.SH DESCRIPTION
Create and edit executable scripts in a directory EDSPATH (defaults to
~/.local/bin). Makes any created files executable for convenience.
.P
   $ eds myscript
   $ eds myscript newscript
   $ EDITOR=vim eds -O tabone tabtwo
.SH AUTHOR
Tom Ryder <tom@sanctum.geek.nz>
