.TH GSCR 1 "July 2016" "Manual page for gscr"
.SH NAME
.B gscr
\- scrub a Git repository to pack it and reduce its size
.SH SYNOPSIS
.B gscr
.br
.B gscr
/path/to/project/.git
.br
.B gscr
/path/to/project1 /path/to/project2
.SH DESCRIPTION
.B gscr
runs the git fsck, reflog --expire, and gc commands to get rid of dangling
commit objects in a repository and pack the repository down as small as
possible. Each command will only run if the one before it exited non-zero.
.SH SEE ALSO
git(1), fgscr(1), isgr(1)
.SH AUTHOR
Tom Ryder <tom@sanctum.geek.nz>
