.TH JFCD 1 "June 2016" "Manual page for jfcd"
.SH NAME
.B jfcd
\- watch a directory and automatically commit changes to it
.SH SYNOPSIS
.B jfcd
/path/to/dir &
.SH DESCRIPTION
.B jfcd
watches a directory recursively with inotifywait(1) and commits all changes
with jfc(1) as it detects them. It logs its output and errors to syslog using
logger(1).
.SH SEE ALSO
git(1), inotifywait(1), jfc(1), logger(1)
.SH AUTHOR
Tom Ryder <tom@sanctum.geek.nz>
