.TH MKCP 1 "July 2016" "Manual page for mkcp"
.SH NAME
.B mkcp
\- create last argument as directory and copy remaining arguments into it
.SH SYNOPSIS
.B mkcp
filea fileb newdir
.br
.B mkcp
filea fileb newdir/newsubdir
.SH DESCRIPTION
.B mkcp
combines mkdir(1) and cp(1) into one call, creating the last argument as a
directory and recursively copying the remaining arguments into it. If the
directory creation fails, the script stops before attempting the copy.
.SH SEE ALSO
mkdir(1), cp(1), mkmv(1)
.SH AUTHOR
Tom Ryder <tom@sanctum.geek.nz>
