.TH PLMU 1 "June 2016" "Manual page for plmu"
.SH NAME
.B plmu
\- upgrade plenv[1] modules with cpanm(1)
.SH SYNOPSIS
.B plmu
.SH DESCRIPTION
.B plmu
iterates through a list of the modules installed in the current plenv(1)
version of Perl, excluding any defined in ~/.plenv/non-cpanm-modules, and
attempts to upgrade each of them, reporting any errors. It does not run any
tests, so it's just a shortcut for your personal Perl installation tinkerings,
and not for any production deployment of plenv[1].
.SH SEE ALSO
[1] plenv: https://github.com/tokuhirom/plenv
.br
cpanm(1)
.SH AUTHOR
Tom Ryder <tom@sanctum.geek.nz>
