.TH RFCF 1 "July 2016" "Manual page for rfcf"
.SH NAME
.B rfcf
\- fetch an RFC from the IETF site and write it to stdout
.SH SYNOPSIS
.B rfc
1918
.SH DESCRIPTION
.B rfcf
retrieves the RFC with the given number from the IETF website and writes its
contents to stdout.
.SH SEE ALSO
rfct(1), rfcr(1)
.SH AUTHOR
Tom Ryder <tom@sanctum.geek.nz>
