.TH RFCR 1 "July 2016" "Manual page for rfcr"
.SH NAME
.B rfcr
\- fetch and format an RFC from the IETF website and view it on a terminal
.SH SYNOPSIS
.B rfcr
1918
.SH DESCRIPTION
.B rfcr
retrieves the RFC with the given number from the IETF website with rfcf(1),
formats it with rfct(1), and passes the output to pit(1) for either pager
display or simple output.
.SH SEE ALSO
rfcf(1), rfct(1)
.SH AUTHOR
Tom Ryder <tom@sanctum.geek.nz>
