.TH RFCT 1 "July 2016" "Manual page for rfct"
.SH NAME
.B rfct
\- format the contents of an RFC for nicer reading
.SH SYNOPSIS
.B rfct
rfc1918.txt
.br
rfcf 1918 |
.B rfct
.SH DESCRIPTION
.B rfct
strips page headers and footers and possibly other rubbish from the ASCII
versions of RFC documents as retrieved from the IETF website and writes them to
stdout.
.SH SEE ALSO
rfcf(1), rfcr(1)
.SH AUTHOR
Tom Ryder <tom@sanctum.geek.nz>
