.TH RNDA 1 "August 2016" "Manual page for rnda"
.SH NAME
.B rnda
\- return a low-quality random choice from the given arguments
.SH SYNOPSIS
.B rnda
.br
arg1 arg2 arg3
.SH DESCRIPTION
.B rnda
prints a random choice from the given arguments. It uses rndi(1), which is not
a high-quality random number source.
.SH SEE ALSO
rndf(1), rndi(1), rndl(1), rndn(6)
.SH AUTHOR
Tom Ryder <tom@sanctum.geek.nz>
