.TH RNDL 1 "August 2016" "Manual page for rndl"
.SH NAME
.B rndl
\- return a low-quality random choice of a random line from files
.SH SYNOPSIS
.B rndl
file
.br
.B rndl
file1 file2 file3
.br
command |
.B rndl
.SH DESCRIPTION
.B rndl
prints a random line from its input, using rndi(1) to choose it.
.SH SEE ALSO
rndi(1), rnda(1), rndf(1), rndn(6)
.SH AUTHOR
Tom Ryder <tom@sanctum.geek.nz>
