.TH RNDS 1 "August 2016" "Manual page for rnds"
.SH NAME
.B rnds
\- try to get a random seed
.SH SYNOPSIS
.B rnds
.B rnds
1024
.SH DESCRIPTION
.B rnds
uses POSIX tools to try and find a random number device on the system and emits
the first field of a cksum(1) based on it as a low-quality random numeric seed.
The only optional argument allows specifying the number of random bytes to
read, defaulting to 32. This is intended as a low-quality seed for rndi(1).
.P
/dev/urandom is tried first, then /dev/arandom, then /dev/random, before the
script gives up and emits nothing.
.SH SEE ALSO
rndi(1), rnda(1), rndf(1), rndl(1), rndn(6)
.SH AUTHOR
Tom Ryder <tom@sanctum.geek.nz>
