.TH SCATTER 1 "May 2014" "Manual page for scatter"
.SH NAME
.B scatter
\- run a command on shoal(1) hosts
.SH SYNOPSIS
.B scatter
.I COMMAND
.SH DESCRIPTION
.B scatter
runs a nominated command on all the hosts returned by shoal(1), and prints the
hostname, stdout, and stderr for each call.
.SH SEE ALSO
shock(1), shoal(1)
.SH AUTHOR
Tom Ryder <tom@sanctum.geek.nz>
