.TH SLSF 1 "July 2016" "Manual page for slsf"
.SH NAME
.B slsf
\- list the first hostname on each line of ssh_config(5) files
.SH SYNOPSIS
.B slsf /etc/ssh_config ~/.ssh_config
.br
cat ~/.ssh_config |
.B slsf
.br
.SH DESCRIPTION
.B slsf
iterates through the ssh_config(5) files given as its input and prints the
first name given on each "Host" line, as long as it contains no wildcards. Most
users will probably want the sls(1) frontend.
.P
Within the file, a comment "### nosls" on its own line will exclude all
following output unless an "### sls" comment is read to resume it again:
.P
    Host wanted1
    Host wanted2
    ### nosls
    Host excluded
    ### sls
    Host wanted3
.SH SEE ALSO
sls(1), sra(1), sta(1), ssh(1), ssh_config(5)
.SH AUTHOR
Tom Ryder <tom@sanctum.geek.nz>
