.TH SRA 1 "May 2014" "Manual page for sra"
.SH NAME
.B sra
\- run a command on sls(1) hosts
.SH SYNOPSIS
.B sra
.I COMMAND
.SH DESCRIPTION
.B sra
runs a nominated command on all the hosts returned by sls(1), and prints the
hostname, stdout, and stderr for each call.
.SH SEE ALSO
sta(1), sls(1)
.SH AUTHOR
Tom Ryder <tom@sanctum.geek.nz>
