.TH STWS 1 "August 2016" "Manual page for stws"
.SH NAME
.B stws
\- strip trailing spaces from files
.SH USAGE
.B stws FILE1 [FILE2 ...]
.SH DESCRIPTION
Applies ed(1) to remove all trailing spaces at the end of lines, if present,
from each of the given files.
.SH SEE ALSO
ed(1), stbl(1)
.SH AUTHOR
Tom Ryder <tom@sanctum.geek.nz>
