.TH TD 1 "February 2016" "Manual page for td"
.SH NAME
.B td
\- manage a to-do file
.SH SYNOPSIS
.B td [EDITOR_OPTS] [--]
.SH DESCRIPTION
Edit a to-do file with full path given in environment variable TODO (defaults
to ~/Todo/todo.markdown), and automatically maintain a changelog via git(1).
.SH SEE ALSO
git(1)
.SH AUTHOR
Tom Ryder <tom@sanctum.geek.nz>

