.TH UNF 1 "August 2016" "Manual page for unf"
.SH NAME
.B unf
\- join lines with leading spaces to the previous line
.SH USAGE
.B unf
FILE
.br
.B unf
<FILE
.br
.B unf
FILE1 FILE2...
.br
curl -I http://www.example.net/ |
.B
unf
.SH DESCRIPTION
Joins lines with leading spaces in the output to the previous line,
such as folded header fields in RFC 822 format messages.
.SH AUTHOR
Tom Ryder <tom@sanctum.geek.nz>
