.TH URLH 1 "August 2016" "Manual page for urlh"
.SH NAME
.B urlh
\- search for URL header values by name
.SH SYNOPSIS
.B urlh
https://www.sanctum.geek.nz/
Content-Type
.SH DESCRIPTION
.B urlh
makes a cURL HEAD request for the given URL, and searches the headers for a key
matching the given name, case-insensitively. It prints any matching values to
stdout.
.SH SEE ALSO
curl(1), urlmt(1)
.SH AUTHOR
Tom Ryder <tom@sanctum.geek.nz>
