.TH URLMT 1 "August 2016" "Manual page for urlmt"
.SH NAME
.B urlmt
\- try to get the MIME type of the document at the given URL
.SH SYNOPSIS
.B urlmt
https://www.sanctum.geek.nz/
.SH DESCRIPTION
.B urlmt
uses urlh(1) to search for a Content-Type header for the given URL, and prints
it with any trailing data (e.g. charset) trimmed off.
.SH SEE ALSO
curl(1), urlh(1)
.SH AUTHOR
Tom Ryder <tom@sanctum.geek.nz>
