.TH VIS 1 "November 2015" "Manual page for vis"
.SH NAME
.B vis
\- create and edit personal scripts
.SH SYNOPSIS
.B vis [EDITOR_OPTS] [--] FILE1 [FILE2...]
.SH DESCRIPTION
Create and edit executable scripts in a directory VISPATH (defaults to
~/.local/bin). Makes any created files executable for convenience.
.P
   $ vis myscript
   $ vis myscript newscript
   $ EDITOR=vim vis -O tabone tabtwo
.SH AUTHOR
Tom Ryder <tom@sanctum.geek.nz>
