.TH XGO 1 "August 2016" "Manual page for xgo"
.SH NAME
.B xgo
\- view the given URL in an appropriate program, falling back on $BROWSER
.SH SYNOPSIS
.B xgo
.SH DESCRIPTION
.B xgo
examines each of its arguments and opens an appropriate program to view it,
falling back on $BROWSER.
.SH SEE ALSO
br(1), xgoc(1)
.SH AUTHOR
Tom Ryder <tom@sanctum.geek.nz>
