.TH XGOC 1 "August 2016" "Manual page for xgoc"
.SH NAME
.B xgoc
\- view an URL in the X clipboard in an appropriate program
.SH SYNOPSIS
.B xgoc
.SH DESCRIPTION
.B xgoc
reads an URL from the X clipboard with xsel(1) and runs xgo(1) on it.
.SH SEE ALSO
br(1), xgoc(1)
.SH AUTHOR
Tom Ryder <tom@sanctum.geek.nz>
