# Emacs-style key bindings
set -o braceexpand
set -o emacs

# Save history
HISTFILE=$HOME/.sh_history
HISTSIZE=$((1 << 12))

# Prompt
PS1='\u@\h:\w\$ '

# Load any supplementary scripts
for kshrc in "$HOME"/.kshrc.d/*.ksh ; do
    [[ -e $kshrc ]] || continue
    . "$kshrc"
done
unset -v kshrc
