# Load ~/.profile regardless of shell version
if [ -e "$HOME"/.profile ] ; then
    . "$HOME"/.profile
fi

# Ensure we're using at least version 2.05. Weird arithmetic syntax needed here
# due to leading zeroes and trailing letters in some 2.x version numbers (e.g.
# 2.05a).
if ! [ -n "$BASH_VERSINFO" ] ; then
    return
elif ((BASH_VERSINFO[0] == 2)) &&
     ((10#${BASH_VERSINFO[1]%%[![:digit:]]*} < 5)) ; then
    return
fi

# Load any supplementary scripts
for sh in "$HOME"/.bash_profile.d/*.bash ; do
    [[ -e $sh ]] && source "$sh"
done
unset -v sh

# If ~/.bashrc exists, source that too; the test for interactivity is in there
if [[ -f $HOME/.bashrc ]] ; then
    source "$HOME"/.bashrc
fi
