# Give up completely if no BASH_VERSINFO (<2.0)
if [ -z "$BASH_VERSINFO" ]; then
    return
fi

# Source Bourne shell profile if it exists
if [[ -r $HOME/.profile ]]; then
    source "$HOME"/.profile
fi

# Source interactive Bash config if it exists
if [[ -r $HOME/.bashrc ]]; then
    source "$HOME"/.bashrc
fi

# Print Bash version
printf 'bash: %s\n' "$BASH_VERSION"

