# Give up completely if no BASH_VERSINFO (<2.0)
if ! [ "$BASH_VERSINFO" ] ; then
    return
fi

# Clear console if possible when logging out
if ((SHLVL == 1)) ; then
    clear_console -q 2>/dev/null
fi

